load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "cli",
    main_class = "ch.usi.inf.luce.expr.cli.Main",
    runtime_deps = [
        "//java/ch/usi/inf/luce/expr/cli",
    ],
)

