load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Java

RULES_JVM_EXTERNAL_TAG = "4.2"

RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

# Maven

ANNOTATIONS_VERSION = "21.0.1"

ANTLR_VERSION = "4.10.1"

APACHE_COMMONS_VERSION = "3.12.0"

APTED_VERSION = "0.1"

CHECKSTYLE_VERSION = "10.3.1"

COWWOC_VERSION = "1.2"

DROPWIZARD_VERSION = "2.1.1"

ECLIPSE_TEXT_VERSION = "3.12.0"

JACKSON_VERSION = "2.13.3"

JAVERS_VERSION = "6.2.3"

JAX_RS_VERSION = "2.1.1"

JCOMMANDER_VERSION = "1.48"

JDT_VERSION = "3.21.0"

JGRAPHT_VERSION = "1.5.1"

JUNIT_VERSION = "4.13.1"

JUNIT_QUICK_CHECK_VERSION = "1.0"

METADATA_EXTRACTOR = "2.16.0"

PICOCLI_VERSION = "4.6.3"

PMD_VERSION = "6.47.0"

SQLITE_VERSION = "3.36.0.3"

SWAGGER_VERSION = "2.2.1"

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        # ANTLR
        maven.artifact("org.antlr", "antlr4", ANTLR_VERSION),
        maven.artifact("org.antlr", "antlr4-runtime", ANTLR_VERSION),
        # Apache Common
        maven.artifact("org.apache.commons", "commons-lang3", APACHE_COMMONS_VERSION),
        # APTED
        maven.artifact("eu.mihosoft.ext.apted", "apted", APTED_VERSION),
        # CheckStyle
        maven.artifact("com.puppycrawl.tools", "checkstyle", CHECKSTYLE_VERSION),
        # Cowwoc
        maven.artifact("org.bitbucket.cowwoc", "diff-match-patch", COWWOC_VERSION),
        # Dropwizard
        maven.artifact("io.dropwizard", "dropwizard-configuration", DROPWIZARD_VERSION),
        maven.artifact("io.dropwizard", "dropwizard-core", DROPWIZARD_VERSION),
        maven.artifact("io.dropwizard", "dropwizard-jersey", DROPWIZARD_VERSION),
        maven.artifact("io.dropwizard", "dropwizard-metrics", DROPWIZARD_VERSION),
        # Jackson
        maven.artifact("com.fasterxml.jackson.core", "jackson-annotations", JACKSON_VERSION),
        maven.artifact("com.fasterxml.jackson.core", "jackson-core", JACKSON_VERSION),
        maven.artifact("com.fasterxml.jackson.core", "jackson-databind", JACKSON_VERSION),
        # JaVers
        maven.artifact("org.javers", "javers-core", JAVERS_VERSION),
        # Jax
        maven.artifact("javax.ws.rs", "javax.ws.rs-api", JAX_RS_VERSION),
        # JDT
        maven.artifact("org.eclipse.jdt", "org.eclipse.jdt.core", JDT_VERSION),
        # Eclipse text (for code formatting)
        maven.artifact("org.eclipse.platform", "org.eclipse.text", ECLIPSE_TEXT_VERSION),
        # JetBrains annotations
        maven.artifact("org.jetbrains", "annotations", ANNOTATIONS_VERSION),
        # JGraphT
        maven.artifact("org.jgrapht", "jgrapht-core", JGRAPHT_VERSION),
        # JUnit
        maven.artifact(
            "junit",
            "junit",
            JUNIT_VERSION,
            testonly = True,
        ),
        # JUnit QuickCheck
        maven.artifact(
            "com.pholser",
            "junit-quickcheck-core",
            JUNIT_QUICK_CHECK_VERSION,
            testonly = True,
        ),
        maven.artifact(
            "com.pholser",
            "junit-quickcheck-generators",
            JUNIT_QUICK_CHECK_VERSION,
            testonly = True,
        ),
        # Metadata Extractor
        maven.artifact("com.drewnoakes", "metadata-extractor", METADATA_EXTRACTOR),
        # PicoCLI
        maven.artifact("info.picocli", "picocli", PICOCLI_VERSION),
        # PMD
        maven.artifact("com.beust", "jcommander", JCOMMANDER_VERSION),
        maven.artifact("net.sourceforge.pmd", "pmd-core", PMD_VERSION),
        maven.artifact("net.sourceforge.pmd", "pmd-java", PMD_VERSION),
        # SQLite (JDBC)
        maven.artifact("org.xerial", "sqlite-jdbc", SQLITE_VERSION),
        # Swagger
        maven.artifact("io.swagger.core.v3", "swagger-integration", SWAGGER_VERSION),
        maven.artifact("io.swagger.core.v3", "swagger-jaxrs2", SWAGGER_VERSION),
        maven.artifact("io.swagger.core.v3", "swagger-models", SWAGGER_VERSION),
    ],
    duplicate_version_warning = "error",
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
