filegroup(
    name = "test",
    srcs = glob([
        "test/*.java",
        "test/definitions.json",
        "test/init_queries.sql",
    ]),
    visibility = [
        "//javatests/ch/usi/inf/luce/expr/analyzer/java:__pkg__",
        "//javatests/ch/usi/inf/luce/expr/analyzer/stats:__pkg__",
    ],
)
