filegroup(
    name = "test",
    srcs = glob([
        "test/*.json",
        "test/*.js",
        "test/*.md",
    ]),
    visibility = [
        "//java/ch/usi/inf/luce/expr/table:__subpackages__",
        "//javatests/ch/usi/inf/luce/expr/table:__subpackages__",
    ],
)
